version: '3'
services:
  mysql:
    image: mysql:8
    platform: linux/arm64/v8
    environment:
      MYSQL_ROOT_PASSWORD: benchr00tp@ss
      MYSQL_DATABASE: benchdb
      MYSQL_USER: benchuser
      MYSQL_PASSWORD: benchp@ss
    ports:
      - "3306:3306"